### ISSUE TITLE
Metadata Usage

### ISSUE THREAD

**Issue by rgeber** [uint/jtd-derive#16]
Hello

`Schema` does include the `Metadata` type. However there is no information on how to use the type other then *By default, `jtd_derive` doesn't generate any metadata*.

Does this mean the feature is not supported at all or are there ways to add metadata to a struct?

cu
Roman

**Comment by uint** [comment]
Hi! Adding metadata is currently not supported.

What's your use case? Off the top of my head, would you expect to be able to do something like the following?

```rs
#[derive(JsonTypedef)]
#[typedef(metadata = "{codegen_ver: \"2\"}")]
struct Foo {
    x: u32,
}
```

**Comment by rgeber** [comment]
Hi

Thanks for your reply.

My use case would be to store additional data for use by the frontend. E.g. a form builder.

This would be an idea:

``` rust
#[derive(JsonTypedef)]
#[typedef(metadata = "{codegen_ver: \"2\"}")]
struct Foo {
   #[typedef(metadata = "{label: \"X coord\", required: true}")]
    x: u32,
}
```

cu
Roman

**Comment by uint** [comment]
Alright, I'll come up with something over the weekend.

**Comment by uint** [comment]
Sorry for the delay.

I got `0.1.3` out with metadata support. I'll add proper docs sometime later (probably next weekend). For now, refer to [these tests](https://github.com/uint/jtd-derive/blob/main/tests/metadata.rs) and LMK if anything's off!
